#!/bin/bash
echo "�� Probando aplicación con MySQL local..."
echo ""
echo "🔍 Verificando conexión a BD..."
mysql -u appuser -p'apppassword123' learning_platform -e "SELECT 'BD Local Funciona' as status;"
echo ""
echo "🚀 Iniciando aplicación..."
echo "👤 Usuarios disponibles:"
echo "   admin@plataforma.edu / password"
echo "   instructor@plataforma.edu / password"
echo "   estudiante@plataforma.edu / password"
echo ""
echo "🌐 Aplicación disponible en: http://$(curl -s ifconfig.me):3000"
echo ""
npm run dev
